### ISSUE TITLE
httpx_client.py code is broken?

### ISSUE THREAD

**Issue by evkornev** [aiortc/aioquic#190]
Hey! I was trying to run examples for [httpx_client.py ](https://github.com/aiortc/aioquic/blob/main/examples/httpx_client.py) and [http3_client.py](https://github.com/aiortc/aioquic/blob/main/examples/http3_client.py) 

So if I run `http3_client.py` like 
`python http3_client.py -v --insecure https://quic.aiortc.org/` I get no issues (i.e. GET request completes ok)

but if I run `httpx_client.py` like
`python httpx_client.py -v --insecure https://quic.aiortc.org/`

I have this output:

```
2021-05-06 06:41:03,673 DEBUG asyncio Using selector: EpollSelector
2021-05-06 06:41:03,825 DEBUG quic [add5e0a5a0307fa1] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2021-05-06 06:41:03,880 DEBUG quic [add5e0a5a0307fa1] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2021-05-06 06:41:03,883 DEBUG quic [add5e0a5a0307fa1] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2021-05-06 06:41:03,885 DEBUG quic [add5e0a5a0307fa1] TLS State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS -> State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE
2021-05-06 06:41:03,887 DEBUG quic [add5e0a5a0307fa1] Discarding epoch Epoch.INITIAL
2021-05-06 06:41:03,889 DEBUG quic [add5e0a5a0307fa1] TLS State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE -> State.CLIENT_EXPECT_CERTIFICATE_VERIFY
2021-05-06 06:41:03,891 DEBUG quic [add5e0a5a0307fa1] TLS State.CLIENT_EXPECT_CERTIFICATE_VERIFY -> State.CLIENT_EXPECT_FINISHED
2021-05-06 06:41:03,894 DEBUG quic [add5e0a5a0307fa1] TLS State.CLIENT_EXPECT_FINISHED -> State.CLIENT_POST_HANDSHAKE
2021-05-06 06:41:03,895 INFO quic [add5e0a5a0307fa1] ALPN negotiated protocol h3
2021-05-06 06:41:03,896 INFO client New session ticket received
2021-05-06 06:41:03,897 DEBUG quic [add5e0a5a0307fa1] Stream 3 created by peer
2021-05-06 06:41:03,897 DEBUG quic [add5e0a5a0307fa1] Stream 7 created by peer
2021-05-06 06:41:03,898 DEBUG quic [add5e0a5a0307fa1] Stream 11 created by peer
2021-05-06 06:41:03,906 INFO quic [add5e0a5a0307fa1] Connection close sent (code 0x0, reason )
2021-05-06 06:41:03,906 DEBUG quic [add5e0a5a0307fa1] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
Traceback (most recent call last):
  File "/test/cujo/helpers/http3_client.py", line 291, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/test/cujo/helpers/http3_client.py", line 188, in run
    response = await client.get(url)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1661, in get
    return await self.request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1425, in request
    response = await self.send(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1510, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1545, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1579, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1620, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/base.py", line 105, in handle_async_request
    raise NotImplementedError()  # pragma: nocover
NotImplementedError
```

As you can see connection is terminated early

**Comment by jlaine** [comment]
It looks like the HTTPX API changed again under my feet, feel free to submit a PR.

**Comment by jlaine** [comment]
The API changes are pretty small, I've added PR #203 to fix this.
