### ISSUE TITLE
All alive connection dead after one of the clients lost connection

### ISSUE THREAD

**Issue by voidf** [aiortc/aioquic#219]
Hi! I'm trying to build a minimal IM system with aioquic. On server side, I use `stream_handler` argument to handle the new inbound connection. To avoid idle timeout error, I make server send heartbeat packet to client periodical

But when one of the connection close unexpectedly (e.g KeyboardInterrupted), the other connection would be affected and finally cause lost connection exception.

What's more, after the server dropped all of the connection, any new inbound connection cannot be established any more.

My code is here:

Server:
```python
import asyncio
from typing import Callable, Deque, Dict, List, Optional, Union, cast


import aioquic
from aioquic.asyncio import QuicConnectionProtocol, serve
from aioquic.quic.configuration import QuicConfiguration
from aioquic.tls import SessionTicket

import random
import traceback

import logging
logging.basicConfig(
	level=logging.DEBUG,  
	format='%(asctime)s<%(filename)s:%(lineno)d>[%(levelname)s]%(message)s',
	datefmt='%H:%M:%S'
)
from loguru import logger

class SessionTicketStore:
    """
    Simple in-memory store for session tickets.
    """
    def __init__(self) -> None:
        self.tickets: Dict[bytes, SessionTicket] = {}

    def add(self, ticket: SessionTicket) -> None:
        self.tickets[ticket.ticket] = ticket

    def pop(self, label: bytes) -> Optional[SessionTicket]:
        return self.tickets.pop(label, None)

import datetime
buffersize = 65536

class QUICServerSession:
    def __init__(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
        self._reader = reader
        self._writer = writer
        self._Q = asyncio.Queue()
        asyncio.ensure_future(self.heartbeat())
        asyncio.ensure_future(self.keep_connect())

    async def heartbeat(self):
        try:
            while 1:
                await asyncio.sleep(20)
                self._writer.write(b'D')
        except:
            logger.warning(traceback.format_exc())
    
    async def keep_connect(self):
        while 1:
            res = await self._reader.read(buffersize)
            if not res:
                self._Q.put_nowait(ConnectionResetError("ConnectionReset"))
                return
            if res == b'd':
                logger.debug(res)
                continue
            else:
                logger.info(res)
                self._Q.put_nowait(res)

    async def send(self, data: str): self._writer.write(data.encode('utf-8'))
    async def recv(self) -> bytes: return await self._Q.get()

worker_pool={}
adapters={}

async def handle_inbound(
    reader: asyncio.StreamReader, 
    writer: asyncio.StreamWriter
):
    data = await reader.read(65536)
    message = data.decode()
    logger.info(message)
    vkey, *meta = message.split(' ', 2)
    if vkey != 'mykey':
        logger.critical(f"Detected invalid key {vkey}")
        return
    ses = QUICServerSession(reader, writer)

    new_name = random.randint(0, 65535)
    while new_name in worker_pool:
        new_name = random.randint(0, 65535)
    worker_pool[new_name] = ses
    logger.info(f"new worker standby ... {new_name}")
    try:
        while 1:
            msg = (await ses.recv()).decode('utf-8')
            logger.info('Received: {}', msg)
    except:
        logger.warning(traceback.format_exc())
    finally:
        logger.warning('Discard {} => ', new_name)
        worker_pool.pop(new_name, '')

    logger.critical("Session exit!")

def inbound_wrapper(reader, writer):
    asyncio.ensure_future(handle_inbound(reader, writer))

if __name__ == "__main__":
    conf = QuicConfiguration(
        is_client=False,
    )

    conf.load_cert_chain('ssl/A.crt', 'ssl/A.key')

    ticket_store = SessionTicketStore()

    server = aioquic.asyncio.serve(
        '0.0.0.0', 8110, 
        configuration=conf, 
        stream_handler=inbound_wrapper,
        session_ticket_fetcher=ticket_store.pop,
        session_ticket_handler=ticket_store.add,
        retry=False
    )

    logger.info(f'QUIC listening on 0.0.0.0 {8110}')

    loop = asyncio.get_event_loop()
    loop.run_until_complete(server)
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        logger.critical(traceback.format_exc())
```

Client:
```python
import aioquic
import json
from loguru import logger
import asyncio
from typing import NoReturn

import logging
logging.basicConfig(
	level=logging.DEBUG,  
	format='%(asctime)s<%(filename)s:%(lineno)d>[%(levelname)s]%(message)s',
	datefmt='%H:%M:%S'
)
buffersize = 65536

class QUICWorkerSession:
    def __init__(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
        self._reader = reader
        self._writer = writer
        self._Q = asyncio.Queue()
        asyncio.ensure_future(self.keep_connect())
    async def keep_connect(self):
        while 1:
            res = await self._reader.read(buffersize)
            if not res:
                raise ConnectionResetError()
            if res == b'D':
                logger.debug('Heartbeat')
                self._writer.write(b'd') # send Heartbeat ACK msg
            else:
                logger.debug(f'Putting {res} into queue')
                self._Q.put_nowait(res)

    async def recv(self) -> bytes: return await self._Q.get()
    async def send(self, data: str) -> NoReturn: self._writer.write(data.encode('utf-8'))

import traceback

import ssl
from aioquic.quic.configuration import QuicConfiguration
from aioquic.asyncio.client import connect

@logger.catch
async def run():
    conf = QuicConfiguration(
        is_client=True,
        verify_mode=ssl.CERT_NONE
    )
    loop = asyncio.get_running_loop()
    async with connect(
        '127.0.0.1',
        8110,
        configuration=conf
    ) as C:
        ses = QUICWorkerSession(*(await C.create_stream()))
        await ses.send('mykey')

        while 1:
            cmd = await ses.recv()
            if cmd == b'kill':
                logger.warning('Kill signal detected')


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())
```
During the test, I start two client instances, then I Ctrl+C one of them. However another one got lost soon even if I didn't do anything.

After the connection lost, I tried to restart the client, but the server seems cannot handle new inbound connection any more.

Here is the log of server and my comments:
```
2021-08-01 20:04:09.739 | DEBUG    | __main__:keep_connect:60 - b'd'
2021-08-01 20:04:23.664 | DEBUG    | __main__:keep_connect:60 - b'd'
2021-08-01 20:04:29.739 | DEBUG    | __main__:keep_connect:60 - b'd'
2021-08-01 20:04:43.664 | DEBUG    | __main__:keep_connect:60 - b'd'
2021-08-01 20:04:49.739 | DEBUG    | __main__:keep_connect:60 - b'd'
2021-08-01 20:05:03.663 | DEBUG    | __main__:keep_connect:60 - b'd' # Work properly
20:05:09<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered # The killed client
20:05:09<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 37
20:05:09<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered
20:05:09<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 38
20:05:10<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered
20:05:10<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 39
20:05:10<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered
20:05:10<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 40
20:05:12<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered
20:05:12<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 41
20:05:14<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered
20:05:14<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 42
20:05:19<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered
20:05:19<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 43
20:05:23<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered # Another client
20:05:23<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 31
20:05:23<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:23<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 32
20:05:24<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:24<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 33
20:05:24<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:24<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 34
20:05:26<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:26<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 35
20:05:28<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered
20:05:28<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 44
20:05:29<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:29<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 36
20:05:34<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:34<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 37
20:05:48<connection.py:664>[DEBUG][e71d4155e4a13bd4] Loss detection triggered
20:05:48<connection.py:2987>[DEBUG][e71d4155e4a13bd4] Sending PING (probe) in packet 46
20:05:49<connection.py:1160>[DEBUG][e71d4155e4a13bd4] Discarding epoch Epoch.ONE_RTT
20:05:49<connection.py:2497>[DEBUG][e71d4155e4a13bd4] QuicConnectionState.CONNECTED -> QuicConnectionState.TERMINATED
2021-08-01 20:05:49.748 | WARNING  | __main__:handle_inbound:95 - Traceback (most recent call last):
  File "c:\TS1.py", line 92, in handle_inbound
    msg = (await ses.recv()).decode('utf-8')
AttributeError: 'ConnectionResetError' object has no attribute 'decode'

2021-08-01 20:05:49.750 | WARNING  | __main__:handle_inbound:97 - Discard 37165 => 
2021-08-01 20:05:49.752 | CRITICAL | __main__:handle_inbound:100 - Session exit!
20:05:54<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:54<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 39
20:06:03<connection.py:1160>[DEBUG][d719f579897b182c] Discarding epoch Epoch.ONE_RTT
20:06:03<connection.py:2497>[DEBUG][d719f579897b182c] QuicConnectionState.CONNECTED -> QuicConnectionState.TERMINATED
2021-08-01 20:06:03.673 | WARNING  | __main__:handle_inbound:95 - Traceback (most recent call last):
  File "c:\TS1.py", line 92, in handle_inbound
    msg = (await ses.recv()).decode('utf-8')
AttributeError: 'ConnectionResetError' object has no attribute 'decode'

2021-08-01 20:06:03.679 | WARNING  | __main__:handle_inbound:97 - Discard 29157 => 
2021-08-01 20:06:03.686 | CRITICAL | __main__:handle_inbound:100 - Session exit!
```

And the 'another' client debug log:
```
2021-08-01 20:04:43.661 | DEBUG    | __main__:keep_connect:28 - Heartbeat
2021-08-01 20:05:03.660 | DEBUG    | __main__:keep_connect:28 - Heartbeat
2021-08-01 20:05:23.667 | DEBUG    | __main__:keep_connect:28 - Heartbeat
20:05:23<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:23<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 34
20:05:23<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:23<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 36
20:05:24<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:24<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 38
20:05:24<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:24<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 40
20:05:26<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:26<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 42
20:05:28<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:28<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 44
20:05:33<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:33<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 46
2021-08-01 20:05:43.661 | DEBUG    | __main__:keep_connect:28 - Heartbeat
20:05:53<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:05:53<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 50
20:06:14<connection.py:664>[DEBUG][d719f579897b182c] Loss detection triggered
20:06:14<connection.py:2987>[DEBUG][d719f579897b182c] Sending PING (probe) in packet 52
20:06:54<connection.py:1160>[DEBUG][d719f579897b182c] Discarding epoch Epoch.ONE_RTT
20:06:54<connection.py:2497>[DEBUG][d719f579897b182c] QuicConnectionState.CONNECTED -> QuicConnectionState.TERMINATED
20:06:54<base_events.py:1707>[ERROR]Task exception was never retrieved
future: <Task finished name='Task-2' coro=<QUICWorkerSession.keep_connect() done, defined at C:\TS2.py:22> exception=ConnectionResetError()>
Traceback (most recent call last):
  File "C:\TS2.py", line 26, in keep_connect
    raise ConnectionResetError()
ConnectionResetError
```

So I wonder:

1. Is the behaviors unexpectedly? Or is there any mistake I made?
2. Any method can make several independent connection like TCP but using aioquic?
3. Is that a good idea to keep a connection using QUIC and sending heartbeat packet?

BTW, I'm using Python 3.8.3

Anyway, thanks for the cool library and your patient reading.

**Comment by voidf** [comment]
Seems it only happen on Windows, it works as my expect on Linux, I guess I should close this, sorry.

**Comment by xtuyaowu** [comment]
@voidf have problem use quic java server and python client can get on touch with you? thanks my weichat: jtyd008
