### ISSUE TITLE
Cannot run aioquic server inside Mininet VM

### ISSUE THREAD

**Issue by Hasan-Aga** [aiortc/aioquic#253]
I am trying to run a QUIC server and client inside Mininet VM, I installed aioquic without problems but when I try to run any example I get this error:
```python
Traceback (most recent call last):
  File "examples/http3_client.py", line 525, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 365, in run
    async with connect(
  File "/usr/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/home/mininet/master/aioquic/src/aioquic/asyncio/client.py", line 82, in connect
    transport, protocol = await loop.create_datagram_endpoint(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1332, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1306, in create_datagram_endpoint
    sock = socket.socket(
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```
To debug I tried the following:

- Installed aioquic on host PC, and I was able to run the examples!
- I then opened the file /usr/lib/python3.8/asyncio/base_events.py and printed family variable and I got this:

> AddressFamily.AF_UNIX
> AddressFamily.AF_UNIX
> AddressFamily.AF_INET6
> AddressFamily.AF_INET6

It seems that the problem has something to do with IP version, how do I tell aioquic to use IPv4 instead of IPv6?

**Comment by Hasan-Aga** [comment]
I am closing the issue that I opened because it seems that it is related only to the Mininet VM, I installed Mininet from source code on an Ubuntu 20.04 virtual machine image and aioquic works fine on it.
