### ISSUE TITLE
java server python client error

### ISSUE THREAD

**Issue by xtuyaowu** [aiortc/aioquic#264]
hi guys：
    i want to http3_client.py as client connect to java netty server but got error

java netty server code:
https://github.com/lostk1ng/quictest
public final class QuicServerExample {

    private static final InternalLogger LOGGER = InternalLoggerFactory.getInstance(QuicServerExample.class);

    private QuicServerExample() { }

    public static void main(String[] args) throws Exception {
        SelfSignedCertificate selfSignedCertificate = new SelfSignedCertificate();
        QuicSslContext context = QuicSslContextBuilder.forServer(
                selfSignedCertificate.privateKey(), null, selfSignedCertificate.certificate())
                .applicationProtocols("http/0.9").build();
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        ChannelHandler codec = new QuicServerCodecBuilder().sslContext(context)
                .maxIdleTimeout(5000, TimeUnit.MILLISECONDS)
                // Configure some limits for the maximal number of streams (and the data) that we want to handle.
                .initialMaxData(10000000)
                .initialMaxStreamDataBidirectionalLocal(1000000)
                .initialMaxStreamDataBidirectionalRemote(1000000)
                .initialMaxStreamsBidirectional(100)
                .initialMaxStreamsUnidirectional(100)

                // Setup a token handler. In a production system you would want to implement and provide your custom
                // one.
                .tokenHandler(InsecureQuicTokenHandler.INSTANCE)
                // ChannelHandler that is added into QuicChannel pipeline.
                .handler(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void channelActive(ChannelHandlerContext ctx) {
                        QuicChannel channel = (QuicChannel) ctx.channel();
                        // Create streams etc..
                    }

                    public void channelInactive(ChannelHandlerContext ctx) {
                        ((QuicChannel) ctx.channel()).collectStats().addListener(f -> {
                            if (f.isSuccess()) {
                                LOGGER.info("Connection closed: {}", f.getNow());
                            }
                        });
                    }

                    @Override
                    public boolean isSharable() {
                        return true;
                    }
                })
                .streamHandler(new ChannelInitializer<QuicStreamChannel>() {
                    @Override
                    protected void initChannel(QuicStreamChannel ch)  {
                        // Add a LineBasedFrameDecoder here as we just want to do some simple HTTP 0.9 handling.
                        ch.pipeline().addLast(new LineBasedFrameDecoder(1024))
                                .addLast(new ChannelInboundHandlerAdapter() {
                            @Override
                            public void channelRead(ChannelHandlerContext ctx, Object msg) {
                                ByteBuf byteBuf = (ByteBuf) msg;
                                try {
                                    if (byteBuf.toString(CharsetUtil.US_ASCII).trim().equals("GET /")) {
                                        ByteBuf buffer = ctx.alloc().directBuffer();
                                        buffer.writeCharSequence("Hello World!\r\n", CharsetUtil.US_ASCII);
                                        // Write the buffer and shutdown the output by writing a FIN.
                                        ctx.writeAndFlush(buffer).addListener(QuicStreamChannel.SHUTDOWN_OUTPUT);
                                    }
                                } finally {
                                    byteBuf.release();
                                }
                            }
                        });
                    }
                }).build();
        try {
            Bootstrap bs = new Bootstrap();
            Channel channel = bs.group(group)
                    .channel(NioDatagramChannel.class)
                    .handler(codec)
                    .bind(new InetSocketAddress(9999)).sync().channel();
            channel.closeFuture().sync();
        } finally {
            group.shutdownGracefully();
        }
    }
}

https://github.com/aiortc/aioquic/blob/main/examples/http3_client.py
python3 examples/http3_client.py --legacy-http https://localhost:9999/

error:
javax.net.ssl.SSLHandshakeException: QUICHE_ERR_TLS_FAIL: error:10000133:SSL routines:OPENSSL_internal:NO_APPLICATION_PROTOCOL
	at io.netty.incubator.codec.quic.Quiche.newException(Quiche.java:669)
	at io.netty.incubator.codec.quic.Quiche.throwIfError(Quiche.java:684)
	at io.netty.incubator.codec.quic.QuicheQuicChannel$QuicChannelUnsafe.connectionRecv(QuicheQuicChannel.java:1274)
	at io.netty.incubator.codec.quic.QuicheQuicChannel.recv(QuicheQuicChannel.java:856)
	at io.netty.incubator.codec.quic.QuicheQuicCodec.lambda$handlerAdded$0(QuicheQuicCodec.java:87)
	at io.netty.incubator.codec.quic.QuicHeaderParser.parse(QuicHeaderParser.java:123)
	at io.netty.incubator.codec.quic.QuicheQuicCodec.handleQuicPacket(QuicheQuicCodec.java:144)
	at io.netty.incubator.codec.quic.QuicheQuicCodec.channelRead(QuicheQuicCodec.java:135)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.incubator.codec.quic.QuicException: QUICHE_ERR_TLS_FAIL
	at io.netty.incubator.codec.quic.Quiche.newException(Quiche.java:660)
	... 23 more

(base) admin@localhost aioquic % python3 examples/http3_client.py --legacy-http https://localhost:9999/
2022-02-08 16:22:12,249 INFO quic [9765a0571d2a9768] Retrying with token (29 bytes)
2022-02-08 16:22:12,301 INFO quic [9765a0571d2a9768] Connection close received (code 0x178, reason )
Traceback (most recent call last):
  File "examples/http3_client.py", line 537, in <module>
    zero_rtt=args.zero_rtt,
  File "/Users/admin/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 376, in run
    wait_connected=not zero_rtt,
  File "/Users/admin/opt/anaconda3/lib/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/Users/admin/Documents/study/workspace/aioquic/src/aioquic/asyncio/client.py", line 90, in connect
    await protocol.wait_connected()
  File "/Users/admin/Documents/study/workspace/aioquic/src/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError

regard
thanks

**Comment by jlaine** [comment]
`http/0.9` is not a valid ALPN protocol, use `hq-interop` if you really want to use legacy HTTP/0.9

**Comment by xtuyaowu** [comment]
@jlaine thanks but how to use hq-interop？

**Comment by xtuyaowu** [comment]
i change from .applicationProtocols("http/0.9").build(); to .applicationProtocols("http/3.0").build();
but still fail
javax.net.ssl.SSLHandshakeException: QUICHE_ERR_TLS_FAIL: error:10000133:SSL routines:OPENSSL_internal:NO_APPLICATION_PROTOCOL

**Comment by jlaine** [comment]
aioquic's `http3_client.py` and `http3_server.py` both support HTTP/3 and HTTP/0.9 out of the box.

I really have no idea how the Java library you are using works.

**Comment by xtuyaowu** [comment]
got thanks @jlaine
