### ISSUE TITLE
ImportError: cannot import name 'asynccontextmanager' on run the examples/http3_client.py

### ISSUE THREAD

**Issue by jingronzhao** [aiortc/aioquic#279]
Traceback (most recent call last):
  File "examples/http3_server.py", line 14, in <module>
    from aioquic.asyncio import QuicConnectionProtocol, serve
  File "/home/jingronzhao/finnaly_make/aioquic/src/aioquic/asyncio/__init__.py", line 1, in <module>
    from .client import connect  # noqa
  File "/home/jingronzhao/finnaly_make/aioquic/src/aioquic/asyncio/client.py", line 4, in <module>
    from contextlib import asynccontextmanager
ImportError: cannot import name 'asynccontextmanager'

when l want to run a examples

**Comment by jlaine** [comment]
We only support Python 3.7 and above, you seem to be running an older Python version.

**Comment by jingronzhao** [comment]
thanks
