### ISSUE TITLE
Cannot import buffer

### ISSUE THREAD

**Issue by M15terHyde** [aiortc/aioquic#302]
A strange bug in the imports. I have previously been able to use the examples/http3_client.py and examples/http3_server.py but trying to use this package to write more examples python fails to import the _buffer module in src/aioquic

To reproduce the issue:
1) open python in the src directory
2) from aioquic import about   (works)
3) from aioquic import buffer   (fail)
```
from aioquic import buffer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/aioquic/src/aioquic/buffer.py", line 1, in <module>
    from ._buffer import Buffer, BufferReadError, BufferWriteError  # noqa
ModuleNotFoundError: No module named 'aioquic._buffer'
```

Something is wrong with buffer.py or with _buffer.pyi / _buffer.c that does not allow python to import it.

I don't understand why the examples http3_client and http3_server work but trying to import it directly they fail.

Looking for guidance on how to circumvent this bug. Thanks in advance.

**Comment by M15terHyde** [comment]
This was caused by my own mistake. I forgot I needed to
`pip install -e .`
