### ISSUE TITLE
EMPTY_RENEGOTIATION_INFO_SCSV cipher suite causing issue

### ISSUE THREAD

**Issue by Karthikdasari0423** [aiortc/aioquic#354]
root@ubuntu:~/aioquic# python3 examples/http3_client.py --ca-certs tests/pycacert.pem https://localhost:4433/ --cipher-suites EMPTY_RENEGOTIATION_INFO_SCSV -v
2023-01-30 06:34:30,989 DEBUG asyncio Using selector: EpollSelector
2023-01-30 06:34:30,999 INFO quic [f119c25c32af50b2] Connection close sent (code 0x0, reason )
2023-01-30 06:34:31,000 DEBUG quic [f119c25c32af50b2] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CLOSING
2023-01-30 06:34:31,601 DEBUG quic [f119c25c32af50b2] Discarding epoch Epoch.INITIAL
2023-01-30 06:34:31,601 DEBUG quic [f119c25c32af50b2] Discarding epoch Epoch.HANDSHAKE
2023-01-30 06:34:31,601 DEBUG quic [f119c25c32af50b2] Discarding epoch Epoch.ONE_RTT
2023-01-30 06:34:31,601 DEBUG quic [f119c25c32af50b2] QuicConnectionState.CLOSING -> QuicConnectionState.TERMINATED
Traceback (most recent call last):
  File "examples/http3_client.py", line 547, in <module>
    asyncio.run(
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 388, in main
    async with connect(
  File "/usr/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/lib/python3.8/dist-packages/aioquic/asyncio/client.py", line 95, in connect
    protocol.connect(addr)
  File "/usr/local/lib/python3.8/dist-packages/aioquic/asyncio/protocol.py", line 60, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "/usr/local/lib/python3.8/dist-packages/aioquic/quic/connection.py", line 483, in connect
    self._connect(now=now)
  File "/usr/local/lib/python3.8/dist-packages/aioquic/quic/connection.py", line 1187, in _connect
    self.tls.handle_message(b"", self._crypto_buffers)
  File "/usr/local/lib/python3.8/dist-packages/aioquic/tls.py", line 1214, in handle_message
    self._client_send_hello(output_buf[Epoch.INITIAL])
  File "/usr/local/lib/python3.8/dist-packages/aioquic/tls.py", line 1400, in _client_send_hello
    self._key_schedule_proxy = KeyScheduleProxy(self._cipher_suites)
  File "/usr/local/lib/python3.8/dist-packages/aioquic/tls.py", line 955, in __init__
    self.__schedules = dict(map(lambda c: (c, KeySchedule(c)), cipher_suites))
  File "/usr/local/lib/python3.8/dist-packages/aioquic/tls.py", line 955, in <lambda>
    self.__schedules = dict(map(lambda c: (c, KeySchedule(c)), cipher_suites))
  File "/usr/local/lib/python3.8/dist-packages/aioquic/tls.py", line 899, in __init__
    self.algorithm = cipher_suite_hash(cipher_suite)
  File "/usr/local/lib/python3.8/dist-packages/aioquic/tls.py", line 997, in cipher_suite_hash
    return CIPHER_SUITES[cipher_suite]()
KeyError: <CipherSuite.EMPTY_RENEGOTIATION_INFO_SCSV: 255>

**Comment by jlaine** [comment]
No idea what you're doing here, that's not a valid cipher suite for QUIC.
