### ISSUE TITLE
Error running examples: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Supertuba12** [aiortc/aioquic#36]
Running the examples results in an error related to the certificate found in tests/.

I have verified that the cert and key get loaded in during server startup. Handshake between client and server seems to go well until cert verification. 

Any thoughts on how to resolve this issue?

---

Python version: 3.7.4

Verbose logging for http3_server.py:
```
python examples/http3_server.py --certificate tests/ssl_cert.pem --private-key tests/ssl_key.pem -v
2019-09-26 11:33:25,103 DEBUG asyncio Using selector: EpollSelector
2019-09-26 11:33:28,039 DEBUG quic [5ee0ffcad1c35b8f] Network path ('::1', 55095, 0, 0) discovered
2019-09-26 11:33:28,040 DEBUG quic [5ee0ffcad1c35b8f] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2019-09-26 11:33:28,045 DEBUG quic [5ee0ffcad1c35b8f] TLS State.SERVER_EXPECT_CLIENT_HELLO -> State.SERVER_EXPECT_FINISHED
2019-09-26 11:33:28,047 DEBUG quic [5ee0ffcad1c35b8f] Discarding epoch Epoch.INITIAL
2019-09-26 11:33:28,048 DEBUG quic [5ee0ffcad1c35b8f] Network path ('::1', 55095, 0, 0) validated by handshake
2019-09-26 11:33:28,057 DEBUG quic [5ee0ffcad1c35b8f] Discarding epoch Epoch.INITIAL
2019-09-26 11:33:28,057 INFO quic [5ee0ffcad1c35b8f] Connection close code 0x12A, reason unable to get local issuer certificate
2019-09-26 11:33:28,057 DEBUG quic [5ee0ffcad1c35b8f] QuicConnectionState.CONNECTED -> QuicConnectionState.DRAINING
2019-09-26 11:33:28,145 DEBUG quic [5ee0ffcad1c35b8f] Discarding epoch Epoch.INITIAL
2019-09-26 11:33:28,146 DEBUG quic [5ee0ffcad1c35b8f] Discarding epoch Epoch.HANDSHAKE
2019-09-26 11:33:28,146 DEBUG quic [5ee0ffcad1c35b8f] Discarding epoch Epoch.ONE_RTT
2019-09-26 11:33:28,146 DEBUG quic [5ee0ffcad1c35b8f] QuicConnectionState.DRAINING -> QuicConnectionState.TERMINATED
```

Traceback produced from http3_client.py:
``` 
python examples/http3_client.py https://localhost:4433/ 
2019-09-26 11:33:28,056 WARNING quic [5ee0ffcad1c35b8f] Error: 298, reason: unable to get local issuer certificate, frame_type: QuicFrameType.CRYPTO
Traceback (most recent call last):
  File "examples/http3_client.py", line 358, in <module>
    run(configuration=configuration, url=args.url, data=args.data)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 250, in run
    session_ticket_handler=save_session_ticket,
  File "/usr/lib64/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/home/supertuba/repos/aioquic/aioquic/asyncio/client.py", line 77, in connect
    await protocol.wait_connected()
  File "/home/supertuba/repos/aioquic/aioquic/asyncio/protocol.py", line 122, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError

```

**Comment by jlaine** [comment]
Hi! I recently added certificate verification, and updated the README:

`python examples/http3_client.py --ca-certs tests/pycacert.pem https://localhost:4433/`

Does this help?

**Comment by Supertuba12** [comment]
Works like a charm now.

**Comment by bw1109** [comment]
hey I am also trying to run aioquic I am also getting an error like
Error: 336, reason: OpenSSL call to X509_STORE_load_locations failed, frame_type: 6
Traceback (most recent call last):
  File "/export/home/bw1109/Dev/env/pipenv/aioquic/examples/http3_client.py", line 443, in <module>
    output_dir=args.output_dir,
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/export/home/bw1109/Dev/env/pipenv/aioquic/examples/http3_client.py", line 310, in run
    session_ticket_handler=save_session_ticket,
  File "/usr/lib64/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/export/home/bw1109/Dev/env/pipenv/lib64/python3.7/site-packages/aioquic/asyncio/client.py", line 89, in connect
    await protocol.wait_connected()
  File "/export/home/bw1109/Dev/env/pipenv/lib64/python3.7/site-packages/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError



Ps: I am trying to run it on a remote server and not on my local machine...Please help me with it.

**Comment by jlaine** [comment]
What version of aioquic is this, this looks like an issue I fixed recently?

**Comment by bw1109** [comment]
QUIC stack conforming with draft-27.
Its the latest version of Quic code from Github (https://github.com/aiortc/aioquic)

**Comment by bw1109** [comment]
How can we run Quic on a server other than the localhost? while trying to write my server name and port number, I got this error. Any help is appreciated.
{REF no: QUIC stack conforming with draft-27}

Traceback (most recent call last):
  File "examples/http3_client.py", line 443, in <module>
    output_dir=args.output_dir,
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 310, in run
    session_ticket_handler=save_session_ticket,
  File "/usr/lib64/python3.7/contextlib.py", line 170, in __aenter__
    return await self.gen.__anext__()
  File "/export/home/bw1109/Dev/env/aioquic/src/aioquic/asyncio/client.py", line 59, in connect
    infos = await loop.getaddrinfo(host, port, type=socket.SOCK_DGRAM)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 789, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by YifangZhang** [comment]
> How can we run Quic on a server other than the localhost? while trying to write my server name and port number, I got this error. Any help is appreciated. {REF no: QUIC stack conforming with draft-27}
> 
> Traceback (most recent call last): File "examples/http3_client.py", line 443, in output_dir=args.output_dir, File "/usr/lib64/python3.7/asyncio/base_events.py", line 584, in run_until_complete return future.result() File "examples/http3_client.py", line 310, in run session_ticket_handler=save_session_ticket, File "/usr/lib64/python3.7/contextlib.py", line 170, in **aenter** return await self.gen.**anext**() File "/export/home/bw1109/Dev/env/aioquic/src/aioquic/asyncio/client.py", line 59, in connect infos = await loop.getaddrinfo(host, port, type=socket.SOCK_DGRAM) File "/usr/lib64/python3.7/asyncio/base_events.py", line 789, in getaddrinfo None, getaddr_func, host, port, family, type, proto, flags) File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -2] Name or service not known

This also stuck me for couple weeks now. If author could provide some functional 2 machine examples, it will greatly help!

**Comment by rthalley** [comment]
This looks like a name problem not a TLS problem as getaddrinfo() is saying "name or service not known".
