### ISSUE TITLE
Release a new version on pypi to make it work under Python3.12

### ISSUE THREAD

**Issue by honglei** [aiortc/aioquic#404]
Env: Win10/Python3.12.0/ aioquic-0.9.21 pylsqpack-0.3.17 pyopenssl-23.2.0

```
PS E:\xx\libs\aioquic-main> python examples/http3_client.py --ca-certs tests/pycacert.pem https://localhost:4433/
2023-10-18 10:45:50,850 ERROR asyncio Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF... 4433, 0, 0))>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF... 4433, 0, 0))>)>
Traceback (most recent call last):
  File "C:\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python312\Lib\asyncio\proactor_events.py", line 589, in _loop_reading
    self._protocol.datagram_received(data, addr)
  File "C:\Python312\Lib\site-packages\aioquic\asyncio\protocol.py", line 135, in datagram_received
    self._quic.receive_datagram(cast(bytes, data), addr, now=self._loop.time())
  File "C:\Python312\Lib\site-packages\aioquic\quic\connection.py", line 1001, in receive_datagram
    is_ack_eliciting, is_probing = self._payload_received(
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\aioquic\quic\connection.py", line 2295, in _payload_received
    frame_handler(context, frame_type, buf)
  File "C:\Python312\Lib\site-packages\aioquic\quic\connection.py", line 1519, in _handle_crypto_frame
    self.tls.handle_message(event.data, self._crypto_buffers)
  File "C:\Python312\Lib\site-packages\aioquic\tls.py", line 1249, in handle_message
    self._client_handle_certificate_verify(input_buf)
  File "C:\Python312\Lib\site-packages\aioquic\tls.py", line 1514, in _client_handle_certificate_verify
    verify_certificate(
  File "C:\Python312\Lib\site-packages\aioquic\tls.py", line 231, in verify_certificate
    ssl.match_hostname(
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'match_hostname'
2023-10-18 10:45:50,911 INFO quic [19b989a4c14823be] Duplicate CRYPTO data received for epoch Epoch.HANDSHAKE
```

**Comment by jlaine** [comment]
You're absolutely right, CI is currently building release `0.9.22`. The wheels should hit PyPI in about 30mn.

**Comment by jlaine** [comment]
Done!
