### ISSUE TITLE
Example -- Connect to google

### ISSUE THREAD

**Issue by aghamir** [aiortc/aioquic#52]
Dear all, 
I want to connect to google via QUIC protocol. I've installed aioquic and used the client such bellow:
`python3 examples/http3_client.py --ca-certs tests/pycacert.pem https://www.google.com` 
I got this error:
```
2019-11-21 13:56:18,956 ERROR quic [838842fd97dd6a51] Could not find a common protocol version
Traceback (most recent call last):
  File "examples/http3_client.py", line 412, in <module>
    print_response=args.print_response,
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "examples/http3_client.py", line 307, in run
    session_ticket_handler=save_session_ticket,
  File "/home/aghamir/quick-test/aioquic/src/aioquic/asyncio/compat.py", line 17, in __aenter__
    return await self.gen.__anext__()
  File "/home/aghamir/quick-test/aioquic/src/aioquic/asyncio/client.py", line 77, in connect
    await protocol.wait_connected()
  File "/home/aghamir/quick-test/aioquic/src/aioquic/asyncio/protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError
```

I am newbie in QUIC protocol and also not sure about Google QUIC URL too. Can you help me into this?

Thanks a lot,

**Comment by jlaine** [comment]
NOTE: The `--ca-certs` command line argument is purely for the case where the server uses a certificate which is not signed by a known authority.

Currently Google's servers don't yet support IETF QUIC, they are still on the protocol's predecessor, Google's experimental QUIC. You can find a list of servers supporting IETF QUIC and HTTP/3 here:

https://bagder.github.io/HTTP3-test/
