### ISSUE TITLE
Many test cases failed under Windows

### ISSUE THREAD

**Issue by honglei** [aiortc/aioquic#72]
```
============================= test session starts =============================
platform win32 -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- d:\ProgramData\Python38\python.exe
cachedir: .pytest_cache
rootdir: E:\data\aioquic-0.8.6
plugins: asyncio-0.10.0
collecting ... collected 300 items

tests/test_asyncio.py::HighLevelTest::test_change_connection_id FAILED   [  0%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve FAILED      [  0%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_ec_certificate FAILED [  1%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_large FAILED [  1%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_with_packet_loss FAILED [  1%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_with_session_ticket FAILED [  2%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_with_sni FAILED [  2%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_with_stateless_retry FAILED [  2%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_with_stateless_retry_bad PASSED [  3%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_with_stateless_retry_bad_original_connection_id PASSED [  3%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_with_version_negotiation FAILED [  3%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_without_client_configuration PASSED [  4%]
tests/test_asyncio.py::HighLevelTest::test_connect_and_serve_writelines FAILED [  4%]
tests/test_asyncio.py::HighLevelTest::test_connect_timeout PASSED        [  4%]
tests/test_asyncio.py::HighLevelTest::test_connect_timeout_no_wait_connected PASSED [  5%]
tests/test_asyncio.py::HighLevelTest::test_key_update FAILED             [  5%]
tests/test_asyncio.py::HighLevelTest::test_ping FAILED                   [  5%]
tests/test_asyncio.py::HighLevelTest::test_ping_parallel FAILED          [  6%]
tests/test_asyncio.py::HighLevelTest::test_server_receives_garbage PASSED [  6%]
tests/test_asyncio_compat.py::AsyncioCompatTest::test_ok PASSED          [  6%]
tests/test_asyncio_compat.py::AsyncioCompatTest::test_raise_exception PASSED [  7%]
tests/test_asyncio_compat.py::AsyncioCompatTest::test_raise_exception_type PASSED [  7%]
tests/test_buffer.py::BufferTest::test_data_slice PASSED                 [  7%]
tests/test_buffer.py::BufferTest::test_pull_bytes PASSED                 [  8%]
tests/test_buffer.py::BufferTest::test_pull_bytes_negative PASSED        [  8%]
tests/test_buffer.py::BufferTest::test_pull_bytes_truncated PASSED       [  8%]
tests/test_buffer.py::BufferTest::test_pull_bytes_zero PASSED            [  9%]
tests/test_buffer.py::BufferTest::test_pull_uint16 PASSED                [  9%]
tests/test_buffer.py::BufferTest::test_pull_uint16_truncated PASSED      [  9%]
tests/test_buffer.py::BufferTest::test_pull_uint32 PASSED                [ 10%]
tests/test_buffer.py::BufferTest::test_pull_uint32_truncated PASSED      [ 10%]
tests/test_buffer.py::BufferTest::test_pull_uint64 PASSED                [ 10%]
tests/test_buffer.py::BufferTest::test_pull_uint64_truncated PASSED      [ 11%]
tests/test_buffer.py::BufferTest::test_pull_uint8 PASSED                 [ 11%]
tests/test_buffer.py::BufferTest::test_pull_uint8_truncated PASSED       [ 11%]
tests/test_buffer.py::BufferTest::test_push_bytes PASSED                 [ 12%]
tests/test_buffer.py::BufferTest::test_push_bytes_truncated PASSED       [ 12%]
tests/test_buffer.py::BufferTest::test_push_bytes_zero PASSED            [ 12%]
tests/test_buffer.py::BufferTest::test_push_uint16 PASSED                [ 13%]
tests/test_buffer.py::BufferTest::test_push_uint32 PASSED                [ 13%]
tests/test_buffer.py::BufferTest::test_push_uint64 PASSED                [ 13%]
tests/test_buffer.py::BufferTest::test_push_uint8 PASSED                 [ 14%]
tests/test_buffer.py::BufferTest::test_seek PASSED                       [ 14%]
tests/test_buffer.py::UintVarTest::test_pull_uint_var_truncated PASSED   [ 14%]
tests/test_buffer.py::UintVarTest::test_push_uint_var_too_big PASSED     [ 15%]
tests/test_buffer.py::UintVarTest::test_size_uint_var PASSED             [ 15%]
tests/test_buffer.py::UintVarTest::test_uint_var PASSED                  [ 15%]
```

**Comment by jlaine** [comment]
Lucky you, you've got the topic for your first PR!

**Comment by honglei** [comment]
1) I found an issue under Windows/Python3.8/asyncio  :  https://bugs.python.org/issue40072 


2) Wireshark cannot capture any packet on port 4433 no matter using selector or proactor event loop , for the first test:
```python
import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
import unittest

from tests.test_asyncio import HighLevelTest
if __name__ == '__main__':
    suite = unittest.TestSuite()

    tests = [HighLevelTest("test_change_connection_id")]
    suite.addTests(tests)

    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)
```

**Comment by honglei** [comment]
Server:
```python
import socket
UDP_IP = "::" # = 0.0.0.0 u IPv4
UDP_PORT = 4433
sock = socket.socket(socket.AF_INET6, # Internet
                     socket.SOCK_DGRAM) # UDP
sock.bind((UDP_IP, UDP_PORT))
while True:
    data, addr = sock.recvfrom(1024) # buffer size is 1024 bytes
    print ("received message:", data)
```
Client:
```python
import socket

UDP_IP = "::1"  # localhost
UDP_PORT = 4433
MESSAGE = b"Hello, World!"


sock = socket.socket(socket.AF_INET6, # Internet
                     socket.SOCK_DGRAM) # UDP

addr = ('::ffff:127.0.0.1', 4433, 0, 0)
sock.sendto( str(addr).encode() , addr)
addr = (UDP_IP, UDP_PORT,0,0)
sock.sendto(str(addr).encode() , addr)

addr = (UDP_IP, UDP_PORT)
sock.sendto(str(addr).encode() , addr)
```

Win7 Result:
```
received message: b"('::1', 4433, 0, 0)"
received message: b"('::1', 4433)"
```
CentOS7 Result:
```
('received message:', "('::ffff:127.0.0.1', 4433, 0, 0)")
('received message:', "('::1', 4433, 0, 0)")
('received message:', "('::1', 4433)")
```
So, you cannot use ('::ffff:127.0.0.1', 4433, 0, 0) connect to server addr ('::', 4433) under Win7

**Comment by honglei** [comment]
after change "127.0.0.1" to "::1", 
```
        run(self.run_server())
        run(run_client_change_connection_id("::1"))
```
I  met the following error:'

```
test_change_connection_id (tests.test_asyncio.HighLevelTest) ... [ac8ee470f56a1cbe] Error: 336, reason: OpenSSL call failed, frame_type: 6
ERROR

======================================================================
ERROR: test_change_connection_id (tests.test_asyncio.HighLevelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\data\aioquic-0.8.6\tests\test_asyncio.py", line 312, in test_change_connection_id
    run(run_client_change_connection_id("::1"))
  File "E:\data\aioquic-0.8.6\tests\utils.py", line 46, in run
    return asyncio.get_event_loop().run_until_complete(coro)
  File "d:\ProgramData\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "E:\data\aioquic-0.8.6\tests\test_asyncio.py", line 306, in run_client_change_connection_id
    async with connect(host, port, configuration=configuration) as client:
  File "d:\ProgramData\Python38\lib\contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "d:\ProgramData\Python38\lib\site-packages\aioquic-0.8.6-py3.8-win-amd64.egg\aioquic\asyncio\client.py", line 79, in connect
    await protocol.wait_connected()
  File "d:\ProgramData\Python38\lib\site-packages\aioquic-0.8.6-py3.8-win-amd64.egg\aioquic\asyncio\protocol.py", line 127, in wait_connected
    await asyncio.shield(self._connected_waiter)
ConnectionError

----------------------------------------------------------------------
Ran 1 test in 0.275s

FAILED (errors=1)
```

**Comment by honglei** [comment]
Wiresharp capture file attached here:

**Comment by honglei** [comment]
The wiresharp captured file:
[quic1.zip](https://github.com/aiortc/aioquic/files/4384850/quic1.zip)

**Comment by jlaine** [comment]
Thanks for digging into this, it sounds like issues with Windows's strong host model.

For now I'm not able to get that far in the CI setup. I'm getting errors related to OpenSSL, how did you install OpenSSL for your tests?

**Comment by honglei** [comment]
Under Windows version of Python has buildin openssl dlls，which located under C:\Python38\DLLs，
I use https://github.com/python/cpython-source-deps/releases for related include and link files. 
Related source codes under https://github.com/python/cpython-source-deps/releases

**Comment by jlaine** [comment]
OK thanks I'll look into this. I've added some debugging code, and it looks like the call to `X509_STORE_load_locations` is the one failing:

https://github.com/aiortc/aioquic/runs/541681942?check_suite_focus=true#step:6:48

 Are you getting the same problem?

In the meantime I've changed the tests to connect to `::1`. I'm not entirely convinced this is the correct thing to do, probably the `connect` function should be reworked, but at least we get a little further in the test suite.

**Comment by jlaine** [comment]
I have committed a couple of fixes, I'm now down to 5 failed tests on Windows:

https://github.com/aiortc/aioquic/runs/541717518?check_suite_focus=true#step:6:402

**Comment by honglei** [comment]
```
X:\Tools\aioquic-master\aioquic-master>pytest
================================================= test session starts =================================================
platform win32 -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: X:\Tools\aioquic-master\aioquic-master
plugins: forked-1.1.3, timeout-1.3.4, xdist-1.31.0
collected 300 items

====================================================== FAILURES =======================================================
____________________________________ QuicConnectionTest.test_send_ping_retransmit _____________________________________

self = <tests.test_connection.QuicConnectionTest testMethod=test_send_ping_retransmit>

    def test_send_ping_retransmit(self):
        with client_and_server() as (client, server):
            consume_events(client)

            # client sends another ping, PING is lost
            client.send_ping(uid=12345)
            self.assertEqual(drop(client), 1)

            # PING is retransmitted and acked
            client._on_ping_delivery(QuicDeliveryState.LOST, (12345,))
>           self.assertEqual(roundtrip(client, server), (1, 1))
E           AssertionError: Tuples differ: (0, 0) != (1, 1)
E
E           First differing element 0:
E           0
E           1
E
E           - (0, 0)
E           + (1, 1)

tests\test_connection.py:1616: AssertionError
____________________________ QuicConnectionTest.test_send_stream_data_over_max_streams_uni ____________________________

self = <tests.test_connection.QuicConnectionTest testMethod=test_send_stream_data_over_max_streams_uni>

    def test_send_stream_data_over_max_streams_uni(self):
        with client_and_server() as (client, server):
            # create streams
            for i in range(128):
                stream_id = i * 4 + 2
                client.send_stream_data(stream_id, b"")
                self.assertFalse(client._streams[stream_id].is_blocked)
            self.assertEqual(len(client._streams_blocked_bidi), 0)
            self.assertEqual(len(client._streams_blocked_uni), 0)
            self.assertEqual(roundtrip(client, server), (0, 0))

            # create one too many -> STREAMS_BLOCKED
            stream_id = 128 * 4 + 2
            client.send_stream_data(stream_id, b"")
            self.assertTrue(client._streams[stream_id].is_blocked)
            self.assertEqual(len(client._streams_blocked_bidi), 0)
            self.assertEqual(len(client._streams_blocked_uni), 1)
>           self.assertEqual(roundtrip(client, server), (1, 1))
E           AssertionError: Tuples differ: (0, 0) != (1, 1)
E
E           First differing element 0:
E           0
E           1
E
E           - (0, 0)
E           + (1, 1)

tests\test_connection.py:1667: AssertionError
=============================================== short test summary info ===============================================
FAILED tests/test_connection.py::QuicConnectionTest::test_send_ping_retransmit - AssertionError: Tuples differ: (0, 0...
FAILED tests/test_connection.py::QuicConnectionTest::test_send_stream_data_over_max_streams_uni - AssertionError: Tup...
=========================================== 2 failed, 317 passed in 51.78s ============================================
```

**Comment by jlaine** [comment]
Right, I'm getting similar failures. It seems that the packet pacing code doesn't play nice with the way I run these tests, so I'm trying to disable it.

**Comment by jlaine** [comment]
OK I've spent a lot more time than I'd like debugging this and it would seem UDP / IPv6 is plain broken with `ProactorEventLoop`:

https://bugs.python.org/issue39148

**Comment by jlaine** [comment]
Alright, the test suite now passes on Windows.

I've also landed a number of fixes for Windows such as:

- use the `certifi` package to have a sane Certificate Authority store for all platforms

- when talking to an IPv4 host, make the client use an IPv4-only socket on Windows

**Comment by honglei** [comment]
Excellent ! Many thanks for your hard working!
