### ISSUE TITLE
WebSocket Server Error

### ISSUE THREAD

**Issue by Hannibal42** [aiortc/aioquic#73]
Hi, 
i tried to use the Websockets with the server and client example but the server throws an exception:

future: <Task finished coro=<WebSocketHandler.run_asgi() done, defined at /root/aioquic/examples/http3_server.py:162> exception=AssertionError()>
Traceback (most recent call last):
  File "/root/aioquic/examples/http3_server.py", line 166, in run_asgi
    await application(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 376, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/staticfiles.py", line 86, in __call__
    assert scope["type"] == "http"
AssertionError

My calls to the server and client looks like this:

python3 /root/aioquic/examples/http3_server.py --certificate /root/aioquic/tests/ssl_cert.pem --private-key /root/aioquic/tests/ssl_key.pem -v

python3 /root/aioquic/examples/http3_client.py --ca-certs /root/aioquic/tests/pycacert.pem wss://[1005::5]:4433/ -v

**Comment by jlaine** [comment]
If you re-read the README file, you'll see the correct path for the WebSocket demo is  `/ws`, not `/`.

If you run the following it should work fine:

`python3 /root/aioquic/examples/http3_client.py --ca-certs /root/aioquic/tests/pycacert.pem wss://[1005::5]:4433/ws -v`
